// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS.FMS.Server.Models;

namespace SOS.FMS.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210211144944_init31")]
    partial class init31
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SOS.FMS.Server.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XAdvLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBankNameDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCalculationMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCalculationModeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGradeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XHusbandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XJoiningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XNa1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNtn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPayMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XPayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XPersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPersonalMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShiftDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSocialSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSAccident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CarOperationalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JobClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubRegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSAccidents");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSAccidentalCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FMSAccidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceStatus")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSAccidentalCheckList");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSAccidentalCheckComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FMSAccidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSAccidentalCheckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mentions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSAccidentalCheckComments");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSAccidentalCheckImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSAccidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSAccidentalCheckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FMSAccidentalCheckImages");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Role")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3288dfef-b2ae-43ee-b719-4636519f0ed9"),
                            FMSUserId = new Guid("3288dfef-b2ae-43ee-b719-4636519f0ed9"),
                            Password = "sa",
                            Role = new Guid("a05d85e6-9d62-457d-9496-615daba5901b"),
                            UserName = "sa"
                        });
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSDailyEvening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EA1")
                        .HasColumnType("bit");

                    b.Property<bool>("EA2")
                        .HasColumnType("bit");

                    b.Property<bool>("EA3")
                        .HasColumnType("bit");

                    b.Property<bool>("EA4")
                        .HasColumnType("bit");

                    b.Property<bool>("EA5")
                        .HasColumnType("bit");

                    b.Property<bool>("EA6")
                        .HasColumnType("bit");

                    b.Property<bool>("EB1")
                        .HasColumnType("bit");

                    b.Property<bool>("EB2")
                        .HasColumnType("bit");

                    b.Property<bool>("EB3")
                        .HasColumnType("bit");

                    b.Property<bool>("EB4")
                        .HasColumnType("bit");

                    b.Property<bool>("EB5")
                        .HasColumnType("bit");

                    b.Property<bool>("EB6")
                        .HasColumnType("bit");

                    b.Property<bool>("EB7")
                        .HasColumnType("bit");

                    b.Property<bool>("EE1")
                        .HasColumnType("bit");

                    b.Property<bool>("EE10")
                        .HasColumnType("bit");

                    b.Property<bool>("EE11")
                        .HasColumnType("bit");

                    b.Property<bool>("EE2")
                        .HasColumnType("bit");

                    b.Property<bool>("EE3")
                        .HasColumnType("bit");

                    b.Property<bool>("EE4")
                        .HasColumnType("bit");

                    b.Property<bool>("EE5")
                        .HasColumnType("bit");

                    b.Property<bool>("EE6")
                        .HasColumnType("bit");

                    b.Property<bool>("EE7")
                        .HasColumnType("bit");

                    b.Property<bool>("EE8")
                        .HasColumnType("bit");

                    b.Property<bool>("EE9")
                        .HasColumnType("bit");

                    b.Property<bool>("EG1")
                        .HasColumnType("bit");

                    b.Property<bool>("EG2")
                        .HasColumnType("bit");

                    b.Property<bool>("EG3")
                        .HasColumnType("bit");

                    b.Property<bool>("EG4")
                        .HasColumnType("bit");

                    b.Property<bool>("EG5")
                        .HasColumnType("bit");

                    b.Property<bool>("EG6")
                        .HasColumnType("bit");

                    b.Property<bool>("EI1")
                        .HasColumnType("bit");

                    b.Property<bool>("EI10")
                        .HasColumnType("bit");

                    b.Property<bool>("EI11")
                        .HasColumnType("bit");

                    b.Property<bool>("EI12")
                        .HasColumnType("bit");

                    b.Property<bool>("EI13")
                        .HasColumnType("bit");

                    b.Property<bool>("EI14")
                        .HasColumnType("bit");

                    b.Property<bool>("EI15")
                        .HasColumnType("bit");

                    b.Property<bool>("EI16")
                        .HasColumnType("bit");

                    b.Property<bool>("EI17")
                        .HasColumnType("bit");

                    b.Property<bool>("EI18")
                        .HasColumnType("bit");

                    b.Property<bool>("EI19")
                        .HasColumnType("bit");

                    b.Property<bool>("EI2")
                        .HasColumnType("bit");

                    b.Property<bool>("EI20")
                        .HasColumnType("bit");

                    b.Property<bool>("EI21")
                        .HasColumnType("bit");

                    b.Property<bool>("EI22")
                        .HasColumnType("bit");

                    b.Property<bool>("EI23")
                        .HasColumnType("bit");

                    b.Property<bool>("EI3")
                        .HasColumnType("bit");

                    b.Property<bool>("EI4")
                        .HasColumnType("bit");

                    b.Property<bool>("EI5")
                        .HasColumnType("bit");

                    b.Property<bool>("EI6")
                        .HasColumnType("bit");

                    b.Property<bool>("EI7")
                        .HasColumnType("bit");

                    b.Property<bool>("EI8")
                        .HasColumnType("bit");

                    b.Property<bool>("EI9")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSDailyEveningChecks");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSDailyMorning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("M1")
                        .HasColumnType("bit");

                    b.Property<bool>("M10")
                        .HasColumnType("bit");

                    b.Property<bool>("M11")
                        .HasColumnType("bit");

                    b.Property<bool>("M12")
                        .HasColumnType("bit");

                    b.Property<bool>("M13")
                        .HasColumnType("bit");

                    b.Property<bool>("M14")
                        .HasColumnType("bit");

                    b.Property<bool>("M15")
                        .HasColumnType("bit");

                    b.Property<bool>("M16")
                        .HasColumnType("bit");

                    b.Property<bool>("M17")
                        .HasColumnType("bit");

                    b.Property<bool>("M18")
                        .HasColumnType("bit");

                    b.Property<bool>("M19")
                        .HasColumnType("bit");

                    b.Property<bool>("M2")
                        .HasColumnType("bit");

                    b.Property<bool>("M20")
                        .HasColumnType("bit");

                    b.Property<bool>("M21")
                        .HasColumnType("bit");

                    b.Property<bool>("M22")
                        .HasColumnType("bit");

                    b.Property<bool>("M23")
                        .HasColumnType("bit");

                    b.Property<bool>("M24")
                        .HasColumnType("bit");

                    b.Property<bool>("M25")
                        .HasColumnType("bit");

                    b.Property<bool>("M3")
                        .HasColumnType("bit");

                    b.Property<bool>("M4")
                        .HasColumnType("bit");

                    b.Property<bool>("M5")
                        .HasColumnType("bit");

                    b.Property<bool>("M6")
                        .HasColumnType("bit");

                    b.Property<bool>("M7")
                        .HasColumnType("bit");

                    b.Property<bool>("M8")
                        .HasColumnType("bit");

                    b.Property<bool>("M9")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subregion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSDailyMorningChecks");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inicidents")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.Property<int>("Violations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FMSDrivers");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSEmergency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CarOperationalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JobClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubRegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSEmergencies");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSEmergencyCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FMSEmergencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceStatus")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSEmergencyCheckList");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSEmergencyCheckComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FMSEmergencyCheckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSEmergencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mentions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSEmergencyCheckComments");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSEmergencyCheckImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSEmergencyCheckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSEmergencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FMSVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FMSEmergencyCheckImages");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FMSRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a05d85e6-9d62-457d-9496-615daba5901b"),
                            Description = "Super Admin",
                            Role = "SA"
                        },
                        new
                        {
                            Id = new Guid("2423c92a-5af1-4612-b2bd-73e6ea702b8e"),
                            Description = "Head Of MT",
                            Role = "HMT"
                        },
                        new
                        {
                            Id = new Guid("7b02511e-379b-47d2-b5ee-8b38de4292ba"),
                            Description = "MT Accounts Manager",
                            Role = "MTAM"
                        },
                        new
                        {
                            Id = new Guid("d255348b-a180-45a2-9cb6-6dbbdc222711"),
                            Description = "Coordinator Emergency , Routine / Accidental maintenance",
                            Role = "CIM"
                        },
                        new
                        {
                            Id = new Guid("0280b129-4d31-4cc3-bdfb-e70eaa381953"),
                            Description = "Coordinator Periodic Maintenance",
                            Role = "CPM"
                        },
                        new
                        {
                            Id = new Guid("363ab761-9106-42c5-99d0-00d94ead6166"),
                            Description = "Regional MTO",
                            Role = "RMTO"
                        },
                        new
                        {
                            Id = new Guid("29d9c3cf-40d1-47e1-80b3-c100058be7c0"),
                            Description = "Regional Accounts Officer",
                            Role = "RAO"
                        });
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Breakdowns")
                        .HasColumnType("int");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FuelAverage")
                        .HasColumnType("float");

                    b.Property<int>("IMEI")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<Guid>("Region")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SIM")
                        .HasColumnType("int");

                    b.Property<Guid>("SubRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicles");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleAccident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Region")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicleAccidents");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleDev", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Breakdowns")
                        .HasColumnType("int");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FuelAverage")
                        .HasColumnType("float");

                    b.Property<long>("IMEI")
                        .HasColumnType("bigint");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<Guid>("Region")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SIM")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehiclesDev");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleScoreCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Breakdowns")
                        .HasColumnType("int");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("float");

                    b.Property<double>("FuelAverage")
                        .HasColumnType("float");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicleScoreCards");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.RegionalOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RegionalOffices");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XVaultStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.SubRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRevenueAuthroity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRevenueAuthroityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SubRegions");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XAdvLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBankNameDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XBasicPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XBloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGradeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XGrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XHusbandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XJoiningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XNa1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNtn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPayMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPersonalMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShiftDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSocialSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XChasisNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEngineNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGasolineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGasolineTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLeasingCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XOtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XPurchaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XPurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XRegistrationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XVehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XVehicleTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
