// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS.FMS.Server.Models;

namespace SOS.FMS.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210121091332_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("IMEI")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SIM")
                        .HasColumnType("int");

                    b.Property<string>("SubRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicles");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleAccident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicleAccidents");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleScoreCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Breakdowns")
                        .HasColumnType("int");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("float");

                    b.Property<double>("FuelAverage")
                        .HasColumnType("float");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicleScoreCards");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.RegionalOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RegionalOffices");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XVaultStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.SubRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRevenueAuthroity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRevenueAuthroityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SubRegions");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XChasisNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEngineNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGasolineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGasolineTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLeasingCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XOtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XPurchaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XPurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XRegistrationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XVehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XVehicleTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
