// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS.FMS.Server.Models;

namespace SOS.FMS.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210127093339_init9")]
    partial class init9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SOS.FMS.Server.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XAdvLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBankNameDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCalculationMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCalculationModeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGradeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XHusbandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XJoiningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XNa1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNtn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPayMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XPayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XPersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPersonalMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShiftDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSocialSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inicidents")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.Property<int>("Violations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FMSDrivers");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Breakdowns")
                        .HasColumnType("int");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FuelAverage")
                        .HasColumnType("float");

                    b.Property<int>("IMEI")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<Guid>("Region")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SIM")
                        .HasColumnType("int");

                    b.Property<Guid>("SubRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicle");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleAccident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Region")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubRegion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicleAccidents");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.FMSVehicleScoreCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Breakdowns")
                        .HasColumnType("int");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("float");

                    b.Property<double>("FuelAverage")
                        .HasColumnType("float");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FMSVehicleScoreCards");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.RegionalOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RegionalOffices");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XVaultStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.SubRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRevenueAuthroity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRevenueAuthroityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SubRegions");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XAdvLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBankNameDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XBasicPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XBloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCadreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDesignationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEobi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGradeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XGrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XHusbandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XJoiningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XNa1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("XNa3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNtn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOfficialMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPayMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPersonalMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReference2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XReligionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XShiftDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XSocialSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XChasisNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XEngineNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGasolineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGasolineTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLeasingCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XOtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XPurchaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XPurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XRegistrationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XStationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("XTotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XVehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XVehicleTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("SOS.FMS.Server.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XAbbrevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRegionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("XrowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
